# Generated by Django 3.2.12 on 2022-04-10 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenseTracker', '0002_incometype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('I', 'Income'), ('E', 'Expense')], default='E', max_length=1)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='expenseTracker.account')),
            ],
        ),
    ]
