# Generated by Django 3.2.12 on 2022-04-16 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenseTracker', '0008_auto_20220416_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transcation_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
